// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUk_EQKjIt1eXJYZnF400bVt7O5V8vGEA',
    appId: '1:964066754594:web:465c27daef474bfe514a7b',
    messagingSenderId: '964066754594',
    projectId: 'eventview-app',
    authDomain: 'eventview-app.firebaseapp.com',
    storageBucket: 'eventview-app.appspot.com',
    measurementId: 'G-2VSE0P4VFQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIJWcI3Sa_gi8V_9aM8xpcHz2vxI1plfU',
    appId: '1:964066754594:android:4532c617b0dbd04c514a7b',
    messagingSenderId: '964066754594',
    projectId: 'eventview-app',
    storageBucket: 'eventview-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlVgaQldChUWX3HuJL-FZFtefsUs5VOHM',
    appId: '1:964066754594:ios:240cd7d2e7b8d6ef514a7b',
    messagingSenderId: '964066754594',
    projectId: 'eventview-app',
    storageBucket: 'eventview-app.appspot.com',
    iosBundleId: 'com.example.eventviewApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlVgaQldChUWX3HuJL-FZFtefsUs5VOHM',
    appId: '1:964066754594:ios:4dac6eae81beade2514a7b',
    messagingSenderId: '964066754594',
    projectId: 'eventview-app',
    storageBucket: 'eventview-app.appspot.com',
    iosBundleId: 'com.example.eventviewApplication1.RunnerTests',
  );
}
